language: python
sudo: false
python:
 - "3.5"
 - "3.6"

install:
 - "pip install flake8"

script:
 - "python run_test.py"
 - "flake8 ."
notifications:
  email:
    on_success: change
    on_failure: always
