language: python
sudo: false
python:
 - "3.5"
 - "3.6"

matrix:
  include:
  - os: osx
    language: generic
    env: NMODE=nikola OS=macOS
    python: '3.7'
    before_install:
    - brew update
    - brew upgrade python
    - python3 -m venv /tmp/venv
    - source /tmp/venv/bin/activate
    - pip install --upgrade-strategy eager -U flake8

install:
 - "pip install flake8"

script:
 - "python run_test.py"
 - "flake8 ."
notifications:
  email:
    on_success: change
    on_failure: always
